Web/NET/10_Northwind_Dashboard/10_Northwind_Dashboard/Controllers/MainController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using _10_Northwind_Dashboard.Models;

namespace _10_Northwind_Dashboard.Controllers
{
    public class MainController : Controller
    {
        private NORTHWNDEntities db = new NORTHWNDEntities();

        // GET: Main
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Shop()
        {
            return View();
        }

        public ActionResult About()
        {
            return View();
        }

        public JsonResult GetProducts()
        {
            var dbResult = db.Products.ToList().Where(x=>x.Discontinued==false);
            var result = (from row in dbResult
                          select new
                          {
                              row.ProductID,
                              row.ProductName,
                              row.UnitPrice,
                              row.UnitsInStock
                          });
            return Json(result, JsonRequestBehavior.AllowGet);
        }
    }
}

Web/NET/10_Northwind_Dashboard/10_Northwind_Dashboard/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nombre de aplicación", "Index", "Main", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Main")</li>
                    <li>@Html.ActionLink("Shop", "Shop", "Main")</li>
                    <li>@Html.ActionLink("About us", "About", "Main")</li>
                    <li>@Html.ActionLink("Log out", "Log_out", "Login")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <!--JQWidgets-->
    @Scripts.Render("~/bundles/jqwidgets")
    @Styles.Render("~/bundles/jqwidgets_css")
</body>
</html>

Web/NET/10_Northwind_Dashboard/10_Northwind_Dashboard/Views/Shared/_Layout_Admin.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nombre de aplicación", "Index", "Dashboard", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Dashboard")</li>
                    <li>@Html.ActionLink("Orders", "Index", "AdminOrders")</li>
                    <li>@Html.ActionLink("Reports", "Index", "AdminSales")</li>
                    <li>@Html.ActionLink("Employees", "Index", "AdminEmployees")</li>
                    <li>@Html.ActionLink("Log out", "Log_out", "Login")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <!--JQWidgets-->
    @Scripts.Render("~/bundles/jqwidgets")
    @Styles.Render("~/bundles/jqwidgets_css")
</body>
</html>

Web/NET/10_Northwind_Dashboard/10_Northwind_Dashboard/Views/Shared/_Layout_Login.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <!--JQWidgets-->
    @Scripts.Render("~/bundles/jqwidgets")
    @Styles.Render("~/bundles/jqwidgets_css")
</body>
</html>